import "@coinbase/onchainkit/styles.css";
import type { Metadata, Viewport } from "next";
import "./globals.css";
import { Providers } from "./providers";
import "./theme.css";

export const viewport: Viewport = {
	width: "device-width",
	initialScale: 1,
};

export async function generateMetadata(): Promise<Metadata> {
	const {
		NEXT_PUBLIC_APP_HERO_IMAGE,
		NEXT_PUBLIC_ONCHAINKIT_PROJECT_NAME,
		NEXT_PUBLIC_URL,
		NEXT_PUBLIC_SPLASH_IMAGE,
		NEXT_PUBLIC_SPLASH_BACKGROUND_COLOR,
	} = process.env;
	return {
		title: NEXT_PUBLIC_ONCHAINKIT_PROJECT_NAME,
		description:
			"Generated by `create-onchain --mini`, a Next.js template for MiniKit",
		other: {
			"fc:frame": JSON.stringify({
				version: "next",
				imageUrl: NEXT_PUBLIC_APP_HERO_IMAGE,
				button: {
					title: `Launch ${NEXT_PUBLIC_ONCHAINKIT_PROJECT_NAME}`,
					action: {
						type: "launch_frame",
						name: NEXT_PUBLIC_ONCHAINKIT_PROJECT_NAME,
						url: NEXT_PUBLIC_URL,
						splashImageUrl: NEXT_PUBLIC_SPLASH_IMAGE,
						splashBackgroundColor: NEXT_PUBLIC_SPLASH_BACKGROUND_COLOR,
					},
				},
			}),
		},
	};
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className="bg-background">
				<Providers>{children}</Providers>
			</body>
		</html>
	);
}
